[package]
name = "cop290_sheet_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rstar = "0.10"
ratatui = "0.26"
crossterm = "0.27"
csv = "1.3"

[[bin]]
name = "spreadsheet"
path = "src/main.rs"